#ifndef BUTTONCONFIG_H_
#define BUTTONCONFIG_H_

#define WAIT_BEFORE_MARK_PUSHED 0x01U
#define WAIT_BEFORE_MARK_CLICKED 0x0U
#define WAIT_BEFORE_MARK_LONGCLICKED 0x96U
#define BUTTON_CHECK_DELAY 0xAU

#endif /* BUTTONCONFIG_H_ */